- avoid unnecessary computations for square problems - bugfix for "on-demand" scaling of the linear system - allow up to three trial evaluations in the soft restoration phase if   evaluation error occurs - added option to include MUMPS into makefiles and configure script, but   no actual interface source code

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -319,7 +319,7 @@ ac_includes_default="\
 #endif"
 
 ac_default_prefix=`pwd`
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os BLUEGENEEXTRA CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CXXLIBS AR ARFLAGS AR_X CC CFLAGS ac_ct_CC F77 FFLAGS ac_ct_F77 FLIBS CPP EGREP BITS_PER_POINTER BIT32FCOMMENT BIT64FCOMMENT RANLIB ac_ct_RANLIB LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXXCPP IPADDLIBS TAUCS_INCFLAGS ASLMAKEFLAGS ASLMAKEFILECMDS ASTYLE ASTYLEFLAGS ipoptlib AMPL_CPPFLAGS IPALLLIBS BUILDBLAS_TRUE BUILDBLAS_FALSE BUILDLAPACK_TRUE BUILDLAPACK_FALSE BUILDHSL_TRUE BUILDHSL_FALSE BUILDMA27_TRUE BUILDMA27_FALSE BUILDMA57_TRUE BUILDMA57_FALSE BUILDMC19_TRUE BUILDMC19_FALSE BUILDBLASDIR_TRUE BUILDBLASDIR_FALSE BUILDLAPACKDIR_TRUE BUILDLAPACKDIR_FALSE BUILDHSLDIR_TRUE BUILDHSLDIR_FALSE HAVE_MA27_TRUE HAVE_MA27_FALSE HAVE_MA57_TRUE HAVE_MA57_FALSE HAVE_MC19_TRUE HAVE_MC19_FALSE HAVE_PARDISO_TRUE HAVE_PARDISO_FALSE HAVE_TAUCS_TRUE HAVE_TAUCS_FALSE HAVE_WSMP_TRUE HAVE_WSMP_FALSE BUILDASLDIR_TRUE BUILDASLDIR_FALSE BUILDAMPLINTERFACE_TRUE BUILDAMPLINTERFACE_FALSE ASLLIB LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os BLUEGENEEXTRA CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CXXLIBS AR ARFLAGS AR_X CC CFLAGS ac_ct_CC F77 FFLAGS ac_ct_F77 FLIBS CPP EGREP BITS_PER_POINTER BIT32FCOMMENT BIT64FCOMMENT RANLIB ac_ct_RANLIB LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXXCPP IPADDLIBS TAUCS_INCFLAGS MUMPS_INCFLAGS ASLMAKEFLAGS ASLMAKEFILECMDS ASTYLE ASTYLEFLAGS ipoptlib AMPL_CPPFLAGS IPALLLIBS BUILDBLAS_TRUE BUILDBLAS_FALSE BUILDLAPACK_TRUE BUILDLAPACK_FALSE BUILDHSL_TRUE BUILDHSL_FALSE BUILDMA27_TRUE BUILDMA27_FALSE BUILDMA57_TRUE BUILDMA57_FALSE BUILDMC19_TRUE BUILDMC19_FALSE BUILDBLASDIR_TRUE BUILDBLASDIR_FALSE BUILDLAPACKDIR_TRUE BUILDLAPACKDIR_FALSE BUILDHSLDIR_TRUE BUILDHSLDIR_FALSE HAVE_MA27_TRUE HAVE_MA27_FALSE HAVE_MA57_TRUE HAVE_MA57_FALSE HAVE_MC19_TRUE HAVE_MC19_FALSE HAVE_PARDISO_TRUE HAVE_PARDISO_FALSE HAVE_TAUCS_TRUE HAVE_TAUCS_FALSE HAVE_MUMPS_TRUE HAVE_MUMPS_FALSE HAVE_WSMP_TRUE HAVE_WSMP_FALSE BUILDASLDIR_TRUE BUILDASLDIR_FALSE BUILDAMPLINTERFACE_TRUE BUILDAMPLINTERFACE_FALSE ASLLIB LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -820,6 +820,10 @@ ac_env_TAUCS_INCFLAGS_set=${TAUCS_INCFLAGS+set}
 ac_env_TAUCS_INCFLAGS_value=$TAUCS_INCFLAGS
 ac_cv_env_TAUCS_INCFLAGS_set=${TAUCS_INCFLAGS+set}
 ac_cv_env_TAUCS_INCFLAGS_value=$TAUCS_INCFLAGS
+ac_env_MUMPS_INCFLAGS_set=${MUMPS_INCFLAGS+set}
+ac_env_MUMPS_INCFLAGS_value=$MUMPS_INCFLAGS
+ac_cv_env_MUMPS_INCFLAGS_set=${MUMPS_INCFLAGS+set}
+ac_cv_env_MUMPS_INCFLAGS_value=$MUMPS_INCFLAGS
 ac_env_ASLMAKEFLAGS_set=${ASLMAKEFLAGS+set}
 ac_env_ASLMAKEFLAGS_value=$ASLMAKEFLAGS
 ac_cv_env_ASLMAKEFLAGS_set=${ASLMAKEFLAGS+set}
@@ -920,6 +924,7 @@ Optional Packages:
   --with-hsl              specify Harwell library (or BUILD for compilation)
   --with-pardiso          specify Pardiso library (unsupported)
   --with-taucs            specify TAUCS library and dependencies
+  --with-mumps            specify MUMPS library and dependencies
   --with-wsmp             specify WSMP library
   --with-asldir           specify absolute path to AMPL solver directory (or
                           BUILD for compilation, or "no" for disabling AMPL)
@@ -943,6 +948,8 @@ Some influential environment variables:
   CXXCPP      C++ preprocessor
   TAUCS_INCFLAGS
               Flags for including taucs header files
+  MUMPS_INCFLAGS
+              Flags for including mumps and (psydo) mpi header files.
   ASLMAKEFLAGS
               Compilation flags necessary for compiling the AMPL solver
               library
@@ -3631,7 +3638,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3634:" \
+echo "$as_me:3641:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4198,7 +4205,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:4201: \"$ac_link\") >&5
+(eval echo $as_me:4208: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -4276,7 +4283,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:4279: \"$ac_link\") >&5
+(eval echo $as_me:4286: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11494,6 +11501,38 @@ _ACEOF
   CXXFLAGS="$CXXFLAGS $TAUCS_INCFLAGS"
 fi
 
+#########
+# MUMPS #
+#########
+
+
+# Check whether --with-mumps or --without-mumps was given.
+if test "${with_mumps+set}" = set; then
+  withval="$with_mumps"
+  use_mumps="$withval"
+else
+  use_mumps=no
+fi;
+
+if test ! "$use_mumps" = "no"; then
+  LIBS="$use_mumps $LIBS"
+  IPADDLIBS="$use_mumps $IPADDLIBS"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MUMPS 1
+_ACEOF
+
+
+
+  if test -z "$MUMPS_INCFLAGS"; then
+    { { echo "$as_me:$LINENO: error: You need to specify MUMPS_INCFLAGS if you want to use MUMPS." >&5
+echo "$as_me: error: You need to specify MUMPS_INCFLAGS if you want to use MUMPS." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  CXXFLAGS="$CXXFLAGS $MUMPS_INCFLAGS"
+fi
+
 ########
 # WSMP #
 ########
@@ -11587,7 +11626,7 @@ else
   distconf=false
 fi;
 
-if test "$use_MA27" = "no" -a "$use_MA57" = "no" -a "$use_pardiso" = "no" -a "$use_taucs" = no -a "$use_wsmp" = no; then
+if test "$use_MA27" = "no" -a "$use_MA57" = "no" -a "$use_pardiso" = "no" -a "$use_taucs" = no -a "$use_wsmp" = no -a "$use_mumps" = no; then
   if test "$distconf" = false; then
     { { echo "$as_me:$LINENO: error: \"No linear solver (such as MA27) available.  You need to provide at least one.\"" >&5
 echo "$as_me: error: \"No linear solver (such as MA27) available.  You need to provide at least one.\"" >&2;}
@@ -12129,6 +12168,16 @@ fi
 
 
 
+if test ! "$use_mumps" = no; then
+  HAVE_MUMPS_TRUE=
+  HAVE_MUMPS_FALSE='#'
+else
+  HAVE_MUMPS_TRUE='#'
+  HAVE_MUMPS_FALSE=
+fi
+
+
+
 if test ! "$use_wsmp" = no; then
   HAVE_WSMP_TRUE=
   HAVE_WSMP_FALSE='#'
@@ -12395,6 +12444,13 @@ if test -z "${HAVE_TAUCS_TRUE}" && test -z "${HAVE_TAUCS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_TAUCS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_TAUCS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MUMPS_TRUE}" && test -z "${HAVE_MUMPS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MUMPS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MUMPS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -13048,6 +13104,7 @@ s,@MAINT@,$MAINT,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@IPADDLIBS@,$IPADDLIBS,;t t
 s,@TAUCS_INCFLAGS@,$TAUCS_INCFLAGS,;t t
+s,@MUMPS_INCFLAGS@,$MUMPS_INCFLAGS,;t t
 s,@ASLMAKEFLAGS@,$ASLMAKEFLAGS,;t t
 s,@ASLMAKEFILECMDS@,$ASLMAKEFILECMDS,;t t
 s,@ASTYLE@,$ASTYLE,;t t
@@ -13083,6 +13140,8 @@ s,@HAVE_PARDISO_TRUE@,$HAVE_PARDISO_TRUE,;t t
 s,@HAVE_PARDISO_FALSE@,$HAVE_PARDISO_FALSE,;t t
 s,@HAVE_TAUCS_TRUE@,$HAVE_TAUCS_TRUE,;t t
 s,@HAVE_TAUCS_FALSE@,$HAVE_TAUCS_FALSE,;t t
+s,@HAVE_MUMPS_TRUE@,$HAVE_MUMPS_TRUE,;t t
+s,@HAVE_MUMPS_FALSE@,$HAVE_MUMPS_FALSE,;t t
 s,@HAVE_WSMP_TRUE@,$HAVE_WSMP_TRUE,;t t
 s,@HAVE_WSMP_FALSE@,$HAVE_WSMP_FALSE,;t t
 s,@BUILDASLDIR_TRUE@,$BUILDASLDIR_TRUE,;t t
