bring Java interface back into stable

diff --git a/Ipopt/configure b/Ipopt/configure
--- a/Ipopt/configure
+++ b/Ipopt/configure
@@ -31491,7 +31491,96 @@ esac
 SHARED_FLAGS=-shared
 
 
-#AC_COIN_LINK_FROM_FILELIST(contrib/JavaInterface,contrib/JavaInterface/javafiles.lst)
+
+
+
+
+echo "$as_me:$LINENO: checking which command should be used to link input files" >&5
+echo $ECHO_N "checking which command should be used to link input files... $ECHO_C" >&6
+coin_link_input_cmd="$LN_S"
+if test "$enable_doscompile" = mingw; then
+  coin_link_input_cmd=cp
+fi
+case "$CC" in
+  cl* | */cl* | CL* | */CL*)
+    coin_link_input_cmd=cp ;;
+esac
+echo "$as_me:$LINENO: result: $coin_link_input_cmd" >&5
+echo "${ECHO_T}$coin_link_input_cmd" >&6
+
+
+
+echo Creating links in contrib/JavaInterface ...
+cmd="$coin_link_input_cmd"
+if test -e $srcdir/contrib/JavaInterface/javafiles.lst ; then
+  my_target_dir="contrib/JavaInterface"
+  my_link_files=`cat $srcdir/contrib/JavaInterface/javafiles.lst`
+  my_dirname=`(dirname contrib/JavaInterface/javafiles.lst) 2>/dev/null ||
+$as_expr Xcontrib/JavaInterface/javafiles.lst : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 Xcontrib/JavaInterface/javafiles.lst : 'X\(//\)[^/]' \| \
+	 Xcontrib/JavaInterface/javafiles.lst : 'X\(//\)$' \| \
+	 Xcontrib/JavaInterface/javafiles.lst : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo Xcontrib/JavaInterface/javafiles.lst |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+#  if test -e $my_target_dir; then : ; else
+#    AS_MKDIR_P($my_target_dir)
+#  fi
+  for i in $my_link_files; do
+    #rm -rf $my_target_dir/$i
+    if test -e $my_target_dir/$i; then : ; else
+      dirn2=`(dirname $my_target_dir/$i) 2>/dev/null ||
+$as_expr X$my_target_dir/$i : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X$my_target_dir/$i : 'X\(//\)[^/]' \| \
+	 X$my_target_dir/$i : 'X\(//\)$' \| \
+	 X$my_target_dir/$i : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X$my_target_dir/$i |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+      if test -e $dirn2; then : ; else
+        { if $as_mkdir_p; then
+    mkdir -p $dirn2
+  else
+    as_dir=$dirn2
+    as_dirs=
+    while test ! -d "$as_dir"; do
+      as_dirs="$as_dir $as_dirs"
+      as_dir=`(dirname "$as_dir") 2>/dev/null ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$as_dir" : 'X\(//\)[^/]' \| \
+	 X"$as_dir" : 'X\(//\)$' \| \
+	 X"$as_dir" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+    done
+    test ! -n "$as_dirs" || mkdir $as_dirs
+  fi || { { echo "$as_me:$LINENO: error: cannot create directory $dirn2" >&5
+echo "$as_me: error: cannot create directory $dirn2" >&2;}
+   { (exit 1); exit 1; }; }; }
+
+      fi
+      $cmd $abs_source_dir/$my_dirname/$i $my_target_dir/$i
+    fi
+  done
+else
+  { echo "$as_me:$LINENO: WARNING: File list file contrib/JavaInterface/javafiles.lst missing!" >&5
+echo "$as_me: WARNING: File list file contrib/JavaInterface/javafiles.lst missing!" >&2;}
+fi
+
+
 
 ##########
 # ASTYLE #
@@ -31635,28 +31724,11 @@ if test $coin_vpath_config = yes; then
 fi
 
 
-                                                                                                                                                                                                                            ac_config_files="$ac_config_files Makefile src/Common/Makefile src/LinAlg/Makefile src/LinAlg/TMatrices/Makefile src/Interfaces/Makefile src/Interfaces/ipopt_addlibs_f.txt src/Interfaces/ipopt_addlibs_cpp.txt src/Algorithm/Makefile src/Algorithm/LinearSolvers/Makefile src/contrib/CGPenalty/Makefile src/Apps/Makefile src/Apps/AmplSolver/Makefile src/Apps/CUTErInterface/Makefile examples/hs071_f/Makefile examples/hs071_f/hs071_f.f examples/Cpp_example/Makefile examples/hs071_cpp/Makefile examples/hs071_c/Makefile examples/ScalableProblems/Makefile test/Makefile test/run_unitTests contrib/MatlabInterface/src/Makefile"
+                                                                                                                                                                                                                                      ac_config_files="$ac_config_files Makefile src/Common/Makefile src/LinAlg/Makefile src/LinAlg/TMatrices/Makefile src/Interfaces/Makefile src/Interfaces/ipopt_addlibs_f.txt src/Interfaces/ipopt_addlibs_cpp.txt src/Algorithm/Makefile src/Algorithm/LinearSolvers/Makefile src/contrib/CGPenalty/Makefile src/Apps/Makefile src/Apps/AmplSolver/Makefile src/Apps/CUTErInterface/Makefile examples/hs071_f/Makefile examples/hs071_f/hs071_f.f examples/Cpp_example/Makefile examples/hs071_cpp/Makefile examples/hs071_c/Makefile examples/ScalableProblems/Makefile test/Makefile test/run_unitTests contrib/MatlabInterface/src/Makefile contrib/JavaInterface/Makefile"
 
 
           ac_config_headers="$ac_config_headers inc/config_ipopt.h"
 
-
-
-
-
-
-echo "$as_me:$LINENO: checking which command should be used to link input files" >&5
-echo $ECHO_N "checking which command should be used to link input files... $ECHO_C" >&6
-coin_link_input_cmd="$LN_S"
-if test "$enable_doscompile" = mingw; then
-  coin_link_input_cmd=cp
-fi
-case "$CC" in
-  cl* | */cl* | CL* | */CL*)
-    coin_link_input_cmd=cp ;;
-esac
-echo "$as_me:$LINENO: result: $coin_link_input_cmd" >&5
-echo "${ECHO_T}$coin_link_input_cmd" >&6
 
 
 
@@ -32412,6 +32484,7 @@ do
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/run_unitTests" ) CONFIG_FILES="$CONFIG_FILES test/run_unitTests" ;;
   "contrib/MatlabInterface/src/Makefile" ) CONFIG_FILES="$CONFIG_FILES contrib/MatlabInterface/src/Makefile" ;;
+  "contrib/JavaInterface/Makefile" ) CONFIG_FILES="$CONFIG_FILES contrib/JavaInterface/Makefile" ;;
   "test/hs071_main.cpp" ) CONFIG_LINKS="$CONFIG_LINKS test/hs071_main.cpp:examples/hs071_cpp/hs071_main.cpp" ;;
   "test/hs071_nlp.cpp" ) CONFIG_LINKS="$CONFIG_LINKS test/hs071_nlp.cpp:examples/hs071_cpp/hs071_nlp.cpp" ;;
   "test/hs071_nlp.hpp" ) CONFIG_LINKS="$CONFIG_LINKS test/hs071_nlp.hpp:examples/hs071_cpp/hs071_nlp.hpp" ;;
