check for -static-lib* flags is now in coin.m4; disabling pthread in mumps now via --disable-pthread-mumps; a bit cleanup in configure.ac

diff --git a/Ipopt/configure b/Ipopt/configure
--- a/Ipopt/configure
+++ b/Ipopt/configure
@@ -471,7 +471,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE have_svnversion IPOPT_SVN_REV EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT COIN_CC_IS_CL_TRUE COIN_CC_IS_CL_FALSE MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX COIN_CXX_IS_CL_TRUE COIN_CXX_IS_CL_FALSE MPICXX CXXLIBS ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS F77 ac_ct_F77 FFLAGS MPIF77 FLIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS BLUEGENEEXTRA AIX_FIX_COMPILER_BUG_TRUE AIX_FIX_COMPILER_BUG_FALSE PKG_CONFIG ac_pt_PKG_CONFIG COIN_HAS_PKGCONFIG_TRUE COIN_HAS_PKGCONFIG_FALSE COIN_PKG_CONFIG_PATH COIN_PKG_CONFIG_PATH_UNINSTALLED BLAS_LIBS BLAS_CFLAGS BLAS_DATA BLAS_DEPENDENCIES BLAS_LIBS_INSTALLED BLAS_CFLAGS_INSTALLED BLAS_DATA_INSTALLED IPOPTLIB_CFLAGS IPOPTLIB_LIBS IPOPTLIB_PCLIBS IPOPTLIB_PCREQUIRES IPOPTLIB_DEPENDENCIES IPOPTLIB_CFLAGS_INSTALLED IPOPTLIB_LIBS_INSTALLED COIN_HAS_BLAS_TRUE COIN_HAS_BLAS_FALSE LAPACK_LIBS LAPACK_CFLAGS LAPACK_DATA LAPACK_DEPENDENCIES LAPACK_LIBS_INSTALLED LAPACK_CFLAGS_INSTALLED LAPACK_DATA_INSTALLED COIN_HAS_LAPACK_TRUE COIN_HAS_LAPACK_FALSE ASL_LIBS ASL_CFLAGS ASL_DATA ASL_DEPENDENCIES ASL_LIBS_INSTALLED ASL_CFLAGS_INSTALLED ASL_DATA_INSTALLED IPOPTAMPLINTERFACELIB_CFLAGS IPOPTAMPLINTERFACELIB_LIBS IPOPTAMPLINTERFACELIB_PCLIBS IPOPTAMPLINTERFACELIB_PCREQUIRES IPOPTAMPLINTERFACELIB_DEPENDENCIES IPOPTAMPLINTERFACELIB_CFLAGS_INSTALLED IPOPTAMPLINTERFACELIB_LIBS_INSTALLED COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE HSL_LIBS HSL_CFLAGS HSL_DATA HSL_DEPENDENCIES HSL_LIBS_INSTALLED HSL_CFLAGS_INSTALLED HSL_DATA_INSTALLED COIN_HAS_HSL_TRUE COIN_HAS_HSL_FALSE MUMPS_LIBS MUMPS_CFLAGS MUMPS_DATA MUMPS_DEPENDENCIES MUMPS_LIBS_INSTALLED MUMPS_CFLAGS_INSTALLED MUMPS_DATA_INSTALLED COIN_HAS_MUMPS_TRUE COIN_HAS_MUMPS_FALSE BITS_PER_POINTER BIT32FCOMMENT BIT64FCOMMENT CXXAR HAVE_MA28_TRUE HAVE_MA28_FALSE JAVA_HOME JIPOPTDLL SHARED_FLAGS MEX_STATIC_TRUE MEX_STATIC_FALSE MEX_WINDOWS_TRUE MEX_WINDOWS_FALSE FRAMEWORK_VECLIB MATLAB_HOME MEXSUFFIX ASTYLE ASTYLEFLAGS IPALLLIBS HAVE_PARDISO_TRUE HAVE_PARDISO_FALSE HAVE_WSMP_TRUE HAVE_WSMP_FALSE BUILD_LINEARSOLVERLOADER_TRUE BUILD_LINEARSOLVERLOADER_FALSE BUILD_PARDISOLOADER_TRUE BUILD_PARDISOLOADER_FALSE BUILD_INEXACT_TRUE BUILD_INEXACT_FALSE LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE have_svnversion IPOPT_SVN_REV EGREP LN_S CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT COIN_CC_IS_CL_TRUE COIN_CC_IS_CL_FALSE MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX COIN_CXX_IS_CL_TRUE COIN_CXX_IS_CL_FALSE MPICXX CXXLIBS ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS F77 ac_ct_F77 FFLAGS MPIF77 FLIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS BLUEGENEEXTRA AIX_FIX_COMPILER_BUG_TRUE AIX_FIX_COMPILER_BUG_FALSE PKG_CONFIG ac_pt_PKG_CONFIG COIN_HAS_PKGCONFIG_TRUE COIN_HAS_PKGCONFIG_FALSE COIN_PKG_CONFIG_PATH COIN_PKG_CONFIG_PATH_UNINSTALLED BLAS_LIBS BLAS_CFLAGS BLAS_DATA BLAS_DEPENDENCIES BLAS_LIBS_INSTALLED BLAS_CFLAGS_INSTALLED BLAS_DATA_INSTALLED IPOPTLIB_CFLAGS IPOPTLIB_LIBS IPOPTLIB_PCLIBS IPOPTLIB_PCREQUIRES IPOPTLIB_DEPENDENCIES IPOPTLIB_CFLAGS_INSTALLED IPOPTLIB_LIBS_INSTALLED COIN_HAS_BLAS_TRUE COIN_HAS_BLAS_FALSE LAPACK_LIBS LAPACK_CFLAGS LAPACK_DATA LAPACK_DEPENDENCIES LAPACK_LIBS_INSTALLED LAPACK_CFLAGS_INSTALLED LAPACK_DATA_INSTALLED COIN_HAS_LAPACK_TRUE COIN_HAS_LAPACK_FALSE ASL_LIBS ASL_CFLAGS ASL_DATA ASL_DEPENDENCIES ASL_LIBS_INSTALLED ASL_CFLAGS_INSTALLED ASL_DATA_INSTALLED IPOPTAMPLINTERFACELIB_CFLAGS IPOPTAMPLINTERFACELIB_LIBS IPOPTAMPLINTERFACELIB_PCLIBS IPOPTAMPLINTERFACELIB_PCREQUIRES IPOPTAMPLINTERFACELIB_DEPENDENCIES IPOPTAMPLINTERFACELIB_CFLAGS_INSTALLED IPOPTAMPLINTERFACELIB_LIBS_INSTALLED COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE HSL_LIBS HSL_CFLAGS HSL_DATA HSL_DEPENDENCIES HSL_LIBS_INSTALLED HSL_CFLAGS_INSTALLED HSL_DATA_INSTALLED COIN_HAS_HSL_TRUE COIN_HAS_HSL_FALSE MUMPS_LIBS MUMPS_CFLAGS MUMPS_DATA MUMPS_DEPENDENCIES MUMPS_LIBS_INSTALLED MUMPS_CFLAGS_INSTALLED MUMPS_DATA_INSTALLED COIN_HAS_MUMPS_TRUE COIN_HAS_MUMPS_FALSE BITS_PER_POINTER BIT32FCOMMENT BIT64FCOMMENT CXXAR HAVE_MA28_TRUE HAVE_MA28_FALSE JAVA_HOME JIPOPTDLL SHARED_FLAGS MEX_WINDOWS_TRUE MEX_WINDOWS_FALSE MEX_STATIC_TRUE MEX_STATIC_FALSE MATLAB_HOME MEXSUFFIX FRAMEWORK_VECLIB ASTYLE ASTYLEFLAGS IPALLLIBS HAVE_PARDISO_TRUE HAVE_PARDISO_FALSE HAVE_WSMP_TRUE HAVE_WSMP_FALSE BUILD_LINEARSOLVERLOADER_TRUE BUILD_LINEARSOLVERLOADER_FALSE BUILD_PARDISOLOADER_TRUE BUILD_PARDISOLOADER_FALSE BUILD_INEXACT_TRUE BUILD_INEXACT_FALSE LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -36274,31 +36274,6 @@ else
   use_matlab_home=
 fi;
 
-# Check whether --enable-matlab-static or --disable-matlab-static was given.
-if test "${enable_matlab_static+set}" = set; then
-  enableval="$enable_matlab_static"
-  case "$enableval" in
-     no | yes) ;;
-     *)
-       { { echo "$as_me:$LINENO: error: invalid argument for --enable-matlab-static: $enableval" >&5
-echo "$as_me: error: invalid argument for --enable-matlab-static: $enableval" >&2;}
-   { (exit 1); exit 1; }; };;
-   esac
-   use_matlab_static=$enableval
-else
-  use_matlab_static=no
-fi;
-
-
-if test "$use_matlab_static" = yes; then
-  MEX_STATIC_TRUE=
-  MEX_STATIC_FALSE='#'
-else
-  MEX_STATIC_TRUE='#'
-  MEX_STATIC_FALSE=
-fi
-
-
 # If we're in Windows, need to add .bat extension to find mex and mexext, and set conditional to modify Matlab interface Makefile
 batext=
 case $build in
@@ -36345,24 +36320,10 @@ echo "$as_me: error: Matlab compiler $MATLAB_HOME/bin/mex$batext not found or no
 fi
 
 MEXSUFFIX=
+FRAMEWORK_VECLIB=
 if test x"$MATLAB_HOME" != x; then
   echo "$as_me:$LINENO: checking for Matlab executable extension (MEXSUFFIX)" >&5
 echo $ECHO_N "checking for Matlab executable extension (MEXSUFFIX)... $ECHO_C" >&6
-
-##   cat >conftest.c <<_ACEOF
-## #include "mex.h"
-## void mexFunction(int nlhs, mxArray *plhs[],
-##   int nrhs, const mxArray *prhs[]) {
-##   int i=0;
-## }
-## _ACEOF
-##   if $MATLAB_HOME/bin/mex conftest.c >5 2>&5; then
-##    MEXSUFFIX=`ls conftest.mex* 5>/dev/null | sed -e 's=conftest.=='`
-##    AC_MSG_RESULT([$MEXSUFFIX])
-##  else
-##    AC_MSG_RESULT([error running MEX compiler])
-##  fi
-
   if ! test -x "$MATLAB_HOME/bin/mexext$batext"; then
     { echo "$as_me:$LINENO: WARNING: Cannot find $MATLAB_HOME/bin/mexext$batext executable to determine MEXSUFFIX" >&5
 echo "$as_me: WARNING: Cannot find $MATLAB_HOME/bin/mexext$batext executable to determine MEXSUFFIX" >&2;}
@@ -36379,13 +36340,38 @@ echo "$as_me: WARNING: Cannot find $MATLAB_HOME/bin/mexext$batext executable to 
     echo "$as_me:$LINENO: result: $MEXSUFFIX" >&5
 echo "${ECHO_T}$MEXSUFFIX" >&6
   fi
+
+  # On Mac, need to move "-framework vecLib" from LIBS to LDFLAGS (if being used)
+  if test -n "`echo $BLAS_LIBS $LAPACK_LIBS | grep -e '-framework vecLib'`"; then
+    FRAMEWORK_VECLIB='-framework vecLib'
+  fi
+
+  # Check whether --enable-matlab-static or --disable-matlab-static was given.
+if test "${enable_matlab_static+set}" = set; then
+  enableval="$enable_matlab_static"
+  case "$enableval" in
+       no | yes) ;;
+       *)
+         { { echo "$as_me:$LINENO: error: invalid argument for --enable-matlab-static: $enableval" >&5
+echo "$as_me: error: invalid argument for --enable-matlab-static: $enableval" >&2;}
+   { (exit 1); exit 1; }; };;
+     esac
+     use_matlab_static=$enableval
+else
+  use_matlab_static=no
+fi;
 fi
 
-# On Mac, need to move "-framework vecLib" from LIBS to LDFLAGS (if being used)
-FRAMEWORK_VECLIB=
-if test -n "`echo $BLAS_LIBS $LAPACK_LIBS | grep -e '-framework vecLib'`"; then
-  FRAMEWORK_VECLIB='-framework vecLib'
+
+
+if test x"$use_matlab_static" = xyes; then
+  MEX_STATIC_TRUE=
+  MEX_STATIC_FALSE='#'
+else
+  MEX_STATIC_TRUE='#'
+  MEX_STATIC_FALSE=
 fi
+
 
 
 
@@ -37944,17 +37930,17 @@ echo "$as_me: error: conditional \"HAVE_MA28\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${MEX_STATIC_TRUE}" && test -z "${MEX_STATIC_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"MEX_STATIC\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"MEX_STATIC\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${MEX_WINDOWS_TRUE}" && test -z "${MEX_WINDOWS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"MEX_WINDOWS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"MEX_WINDOWS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${MEX_STATIC_TRUE}" && test -z "${MEX_STATIC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MEX_STATIC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MEX_STATIC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -38771,13 +38757,13 @@ s,@HAVE_MA28_FALSE@,$HAVE_MA28_FALSE,;t t
 s,@JAVA_HOME@,$JAVA_HOME,;t t
 s,@JIPOPTDLL@,$JIPOPTDLL,;t t
 s,@SHARED_FLAGS@,$SHARED_FLAGS,;t t
-s,@MEX_STATIC_TRUE@,$MEX_STATIC_TRUE,;t t
-s,@MEX_STATIC_FALSE@,$MEX_STATIC_FALSE,;t t
 s,@MEX_WINDOWS_TRUE@,$MEX_WINDOWS_TRUE,;t t
 s,@MEX_WINDOWS_FALSE@,$MEX_WINDOWS_FALSE,;t t
-s,@FRAMEWORK_VECLIB@,$FRAMEWORK_VECLIB,;t t
+s,@MEX_STATIC_TRUE@,$MEX_STATIC_TRUE,;t t
+s,@MEX_STATIC_FALSE@,$MEX_STATIC_FALSE,;t t
 s,@MATLAB_HOME@,$MATLAB_HOME,;t t
 s,@MEXSUFFIX@,$MEXSUFFIX,;t t
+s,@FRAMEWORK_VECLIB@,$FRAMEWORK_VECLIB,;t t
 s,@ASTYLE@,$ASTYLE,;t t
 s,@ASTYLEFLAGS@,$ASTYLEFLAGS,;t t
 s,@IPALLLIBS@,$IPALLLIBS,;t t
