make sure things work if HSL not present at all

diff --git a/Ipopt/configure b/Ipopt/configure
--- a/Ipopt/configure
+++ b/Ipopt/configure
@@ -29429,9 +29429,64 @@ else
   use_hsl=BUILD
 fi;
 
+# First check if there is a working HSL ThirdParty project
 if test "$use_hsl" = BUILD; then
-# Check which files are available
-  as_ac_File=`echo "ac_cv_file_$hslsrcdir/ma27ad.f" | $as_tr_sh`
+  as_ac_File=`echo "ac_cv_file_$hslobjdir/Makefile" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $hslobjdir/Makefile" >&5
+echo $ECHO_N "checking for $hslobjdir/Makefile... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$hslobjdir/Makefile"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  :
+else
+  use_hsl=
+fi
+
+fi
+
+if test "$use_hsl" = BUILD; then
+  # First check if there is a working HSL ThirdParty project
+  as_ac_File=`echo "ac_cv_file_$hslobjdir/Makefile" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $hslobjdir/Makefile" >&5
+echo $ECHO_N "checking for $hslobjdir/Makefile... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$hslobjdir/Makefile"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  :
+else
+  use_hsl=unavailable
+fi
+
+
+  if test "$use_hsl" = BUILD; then
+    # Check which files are available
+    as_ac_File=`echo "ac_cv_file_$hslsrcdir/ma27ad.f" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $hslsrcdir/ma27ad.f" >&5
 echo $ECHO_N "checking for $hslsrcdir/ma27ad.f... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
@@ -29459,17 +29514,17 @@ else
   use_MA27=no
 fi
 
-## This test is already done in ThirdParty configure
-#  if test "$use_MA27" = BUILD; then
-#    AC_MSG_CHECKING([whether MA27 is threadsafe])
-#    if $EGREP MA27UD $hslsrcdir/ma27ad.f >/dev/null 2>&1; then
-#      AC_MSG_RESULT(yes)
-#    else
-#      AC_MSG_RESULT(no)
-#      AC_MSG_ERROR([Please obtain the threadsafe (newer) version of MA27])
-#    fi
-#  fi
-  as_ac_File=`echo "ac_cv_file_$hslsrcdir/mc19ad.f" | $as_tr_sh`
+    ## This test is already done in ThirdParty configure
+    #  if test "$use_MA27" = BUILD; then
+    #    AC_MSG_CHECKING([whether MA27 is threadsafe])
+    #    if $EGREP MA27UD $hslsrcdir/ma27ad.f >/dev/null 2>&1; then
+    #      AC_MSG_RESULT(yes)
+    #    else
+    #      AC_MSG_RESULT(no)
+    #      AC_MSG_ERROR([Please obtain the threadsafe (newer) version of MA27])
+    #    fi
+    #  fi
+    as_ac_File=`echo "ac_cv_file_$hslsrcdir/mc19ad.f" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $hslsrcdir/mc19ad.f" >&5
 echo $ECHO_N "checking for $hslsrcdir/mc19ad.f... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
@@ -29497,7 +29552,7 @@ else
   use_MC19=no
 fi
 
-  as_ac_File=`echo "ac_cv_file_$hslsrcdir/ma57ad.f" | $as_tr_sh`
+    as_ac_File=`echo "ac_cv_file_$hslsrcdir/ma57ad.f" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $hslsrcdir/ma57ad.f" >&5
 echo $ECHO_N "checking for $hslsrcdir/ma57ad.f... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
@@ -29525,7 +29580,7 @@ else
   use_MA57=no
 fi
 
-  as_ac_File=`echo "ac_cv_file_$hslsrcdir/ma28ad.f" | $as_tr_sh`
+    as_ac_File=`echo "ac_cv_file_$hslsrcdir/ma28ad.f" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $hslsrcdir/ma28ad.f" >&5
 echo $ECHO_N "checking for $hslsrcdir/ma28ad.f... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
@@ -29553,7 +29608,8 @@ else
   use_MA28=no
 fi
 
-  coin_need_flibs=yes
+    coin_need_flibs=yes
+  fi
 else
   SAVE_LIBS="$LIBS"
   LIBS="$use_hsl $LIBS $FLIBS"
