don't check for pardiso_exist_parallel if PARDISO from MKL; give only a warning if OMP_NUM_THREADS is not set when using parallel non-MKL PARDISO and continue in sequential mode, ref #216
svn-id: 2370 @trunk

diff --git a/Ipopt/configure b/Ipopt/configure
--- a/Ipopt/configure
+++ b/Ipopt/configure
@@ -35872,53 +35872,6 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-# Test if this is the parallel version of Pardiso
-  echo "$as_me:$LINENO: checking whether Pardiso library is the parallel version" >&5
-echo $ECHO_N "checking whether Pardiso library is the parallel version... $ECHO_C" >&6
-  cat >conftest.$ac_ext <<_ACEOF
-      program main
-      call pardiso_exist_parallel()
-      end
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_f77_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_PARDISO_PARALLEL 1
-_ACEOF
-
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-
   echo "$as_me:$LINENO: checking whether Pardiso library is at least version 4.0" >&5
 echo $ECHO_N "checking whether Pardiso library is at least version 4.0... $ECHO_C" >&6
   cat >conftest.$ac_ext <<_ACEOF
@@ -35967,10 +35920,69 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_PARDISO_MKL 1
 _ACEOF
 
+               else
+                 have_mkl=no
                fi
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+
+# Test if this is the parallel version of Pardiso
+# (MKL PARDISO is always parallel, even though it does not have this function implemented)
+  pardiso_parallel=no
+  if test "$have_mkl" = "yes" ; then
+    pardiso_parallel=yes
+  else
+    echo "$as_me:$LINENO: checking whether Pardiso library is the parallel version" >&5
+echo $ECHO_N "checking whether Pardiso library is the parallel version... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call pardiso_exist_parallel()
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_f77_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                 pardiso_parallel=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  fi
+  if test "$pardiso_parallel" = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PARDISO_PARALLEL 1
+_ACEOF
+
+  fi
+
   LIBS="$SAVE_LIBS"
   IPOPTLIB_LIBS="$PARDISO_LIB $IPOPTLIB_LIBS"
   IPOPTLIB_PCLIBS="$PARDISO_LIB $IPOPTLIB_PCLIBS"
