corrections for MUMPS configuration and debug compile

diff --git a/Ipopt/configure b/Ipopt/configure
--- a/Ipopt/configure
+++ b/Ipopt/configure
@@ -30177,7 +30177,19 @@ else
 fi;
 
 if test "$use_mumps" != "no"; then
-  mumps_dir="$use_mumps"
+  if test -d $use_mumps; then :; else
+    { { echo "$as_me:$LINENO: error: User provided MUMPS directory $use_mumps does not exist." >&5
+echo "$as_me: error: User provided MUMPS directory $use_mumps does not exist." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  mumps_dir=`cd $use_mumps; pwd`
+
+  # library extension
+  case "$CC" in
+    cl* | */cl* | CL* | */CL*)
+         libe=lib ;;
+      *) libe=a ;;
+  esac
 
   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -30297,8 +30309,8 @@ fi
 
   CPPFLAGS="$CPPFLAGS -I$mumps_dir/libseq -I$mumps_dir/include"
 
-  LIBS="-L$mumps_dir/lib -ldmumps -lpord -L$mumps_dir/libseq -lmpiseq $LIBS"
-  ADDLIBS="-L$mumps_dir/lib -ldmumps -lpord -L$mumps_dir/libseq -lmpiseq $ADDLIBS"
+  LIBS="$mumps_dir/lib/libdmumps.$libe $mumps_dir/lib/libpord.$libe $mumps_dir/libseq/libmpiseq.$libe $LIBS"
+  ADDLIBS="$mumps_dir/lib/libdmumps.$libe $mumps_dir/lib/libpord.$libe $mumps_dir/libseq/libmpiseq.$libe $ADDLIBS"
   # Check if MUMPS actually works
   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
