merge r2367-2379,2384-2385 from trunk; disable automatic recognition of mkl/pardiso (still experimental)
svn-id: 2386 @3.11

diff --git a/Ipopt/configure b/Ipopt/configure
--- a/Ipopt/configure
+++ b/Ipopt/configure
@@ -35777,6 +35777,25 @@ else
   use_pardiso=no
 fi;
 
+# Check whether MKL is being used
+have_mkl=no
+#SAVE_LIBS="$LIBS"
+#if test "$use_pardiso" = "no"; then
+#  LIBS="$LIBS $LAPACK_LIBS $BLAS_LIBS"
+#else
+#  LIBS="$use_pardiso $LIBS $LAPACK_LIBS $BLAS_LIBS"
+#fi
+#AC_MSG_CHECKING([whether MKL is being used])
+#AC_TRY_LINK([],[      call mkl_get_version_string()],
+#            [AC_MSG_RESULT(yes)
+#             have_mkl=yes],
+#            [AC_MSG_RESULT(no)])
+# If using MKL, always enable Pardiso
+#if test "$have_mkl" = "yes" -a "$use_pardiso" = "no"; then
+#  use_pardiso=""
+#fi
+#LIBS="$SAVE_LIBS"
+
 if test "$use_pardiso" != "no"; then
   SAVE_LIBS="$LIBS"
   PARDISO_LIB="$use_pardiso"
@@ -35831,53 +35850,6 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-# Test if this is the parallel version of Pardiso
-  echo "$as_me:$LINENO: checking whether Pardiso library is the parallel version" >&5
-echo $ECHO_N "checking whether Pardiso library is the parallel version... $ECHO_C" >&6
-  cat >conftest.$ac_ext <<_ACEOF
-      program main
-      call pardiso_exist_parallel()
-      end
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_f77_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_PARDISO_PARALLEL 1
-_ACEOF
-
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-
   echo "$as_me:$LINENO: checking whether Pardiso library is at least version 4.0" >&5
 echo $ECHO_N "checking whether Pardiso library is at least version 4.0... $ECHO_C" >&6
   cat >conftest.$ac_ext <<_ACEOF
@@ -35920,9 +35892,75 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_PARDISO_OLDINTERFACE 1
 _ACEOF
 
+               if test "$have_mkl" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PARDISO_MKL 1
+_ACEOF
+
+               else
+                 have_mkl=no
+               fi
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+
+# Test if this is the parallel version of Pardiso
+# (MKL PARDISO is always parallel, even though it does not have this function implemented)
+  pardiso_parallel=no
+  if test "$have_mkl" = "yes" ; then
+    pardiso_parallel=yes
+  else
+    echo "$as_me:$LINENO: checking whether Pardiso library is the parallel version" >&5
+echo $ECHO_N "checking whether Pardiso library is the parallel version... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call pardiso_exist_parallel()
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_f77_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                 pardiso_parallel=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  fi
+  if test "$pardiso_parallel" = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PARDISO_PARALLEL 1
+_ACEOF
+
+  fi
+
   LIBS="$SAVE_LIBS"
   IPOPTLIB_LIBS="$PARDISO_LIB $IPOPTLIB_LIBS"
   IPOPTLIB_PCLIBS="$PARDISO_LIB $IPOPTLIB_PCLIBS"
